version: '3.4'

services:
  staplepuck.api:
    image: 398055399259.dkr.ecr.us-east-1.amazonaws.com/staplepuckapi
    build:
      context: .
      dockerfile: src/StaplePuck.API/Dockerfile
    env_file:
      - ./StaplePuck.env
